In [1]:
#1. Write a Python Program to Add Two Matrices?

import numpy as np
a = np.matrix([[7,8,9],[5,4,3],[1,2,0]])
print('Matrix a :\n',a)
b = np.matrix([[1,1,1],[0,0,0],[0,0,1]])
print('Matrix b :\n',b)
C = a + b
print('Addition of matrix a and matrix b is :- \n{}'.format(C))

Matrix a :
 [[7 8 9]
 [5 4 3]
 [1 2 0]]
Matrix b :
 [[1 1 1]
 [0 0 0]
 [0 0 1]]
Addition of matrix a and matrix b is :- 
[[ 8  9 10]
 [ 5  4  3]
 [ 1  2  1]]


In [2]:
#2. Write a Python Program to Multiply Two Matrices?

import numpy as np
a = np.matrix([[9,10],[5,4]])
print('Matrix a :\n',a)
b = np.matrix([[1,1],[0,0]])
print('Matrix b :\n',b)
C = a * b
print('Multiplication of matrix a and matrix b is :- \n{}'.format(C))

Matrix a :
 [[ 9 10]
 [ 5  4]]
Matrix b :
 [[1 1]
 [0 0]]
Multiplication of matrix a and matrix b is :- 
[[9 9]
 [5 5]]


In [3]:
#3. Write a Python Program to Transpose a Matrix?

Mat = np.mat([[1,8,9],[9,2,3],[0,2,0]])
print("Matrix Before Transpose :\n",Mat)
print("Matrix After Transpose : \n",Mat.T)

Matrix Before Transpose :
 [[1 8 9]
 [9 2 3]
 [0 2 0]]
Matrix After Transpose : 
 [[1 9 0]
 [8 2 2]
 [9 3 0]]


In [4]:
#4. Write a Python Program to Sort Words in Alphabetic Order?

str1 = (input("Enter the String : "))
print('Unsorted word :',str1)
li = list(str1)
li.sort()
print("Sorted Word : ",*li,sep='')

Enter the String : takalkar
Unsorted word : takalkar
Sorted Word : aaakklrt


In [13]:
# 5. Write a Python Program to Remove Punctuation From a String?

def rem_punctuation(str):
    punctuation = '''!()-[]{};:'"\, <>./?@#$%^&*_~'''
    for i in str:
        if i in punctuation:
            str = str.replace(i,"")
    print("String without punctuation is : ",str)        
rem_punctuation(input("Enter the string with punctuation:- "))           

Enter the string with punctuation:- ma'[;n!th$@?a%n
String without punctuation is :  manthan
